### ISSUE TITLE
[Bug] Crash using it with some mods

### ISSUE THREAD

**Issue by AnidemDex** [melontini/recipe_book_is_pain#17]
**Describe the bug**
Incompatibility with Botania fabric mod. Game crash on load

**To Reproduce**
1. Install botania and dependences
2. Install recipe book is pain

**Expected behavior**
Game starts

**Screenshots**
None

**Logs**
<details>

<summary>Crash log</summary>

```java
[19:25:48] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.21
[19:25:49] [ForkJoinPool-1-worker-1/WARN]: The mod "moreculling" contains invalid entries in its mod json:
- Unsupported root entry "embedded" at line 35 column 13
[19:25:49] [ForkJoinPool-1-worker-2/WARN]: Mod ultris_mr uses the version 5.6.7g which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7g'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:25:50] [ForkJoinPool-1-worker-1/WARN]: Mod flywheel uses the version 0.6.8.a-5 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:25:50] [ForkJoinPool-1-worker-1/WARN]: Mod globalpacks uses the version 1.14.3.1_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:25:50] [ForkJoinPool-1-worker-2/WARN]: Mod inventorytabs uses the version 0.9.beta-1.19.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'beta'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:25:50] [main/WARN]: Warnings were found!
 - Mod 'Simply Swords' (simplyswords) 1.43.0-1.19.2 recommends version 1.3.2 or later of bettercombat, which is missing!
	 - You should install version 1.3.2 or later of bettercombat for the optimal experience.
[19:25:50] [main/INFO]: Loading 247 mods:
	- advanced-tooltips 1.6.0+1.19
	   \-- advanced-tooltips-core 1.6.0
	- advanced-xray-fabric 1.19-1.1.0-build.12
	- advancementinfo 1.19.1-fabric0.58.5-1.3.1
	- another_furniture 2.1.2-1.19.2
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.85
	- axolotlitemfix 1.1.4
	- basicshields 1.4.0-1.19.2
	   \-- crowdin-translate 1.4+1.19
	- bclib 2.1.7
	- bebooks 1.4.2
	- beekeeperhut 1.2.0
	- betterend 2.1.6
	- boatiview 0.0.4
	- bookshelf 16.3.20
	- bosses_of_mass_destruction 1.4.6-1.19.2
	   |-- maelstrom_library 1.3-1.19-pre1
	   \-- multipart_entities 1.2-1.19-pre1
	- botania 1.19.2-440-FABRIC
	   |-- fiber 0.23.0-2
	   |-- reach-entity-attributes 2.3.0
	   \-- step-height-entity-attribute 1.0.0
	- c2me 0.2.0+alpha.9.9
	   |-- c2me-base 0.2.0+alpha.9.9
	   |-- c2me-client-uncapvd 0.2.0+alpha.9.9
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.9
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.9
	   |-- c2me-notickvd 0.2.0+alpha.9.9
	   |-- c2me-opts-allocs 0.2.0+alpha.9.9
	   |-- c2me-opts-chunk-access 0.2.0+alpha.9.9
	   |-- c2me-opts-chunkio 0.2.0+alpha.9.9
	   |-- c2me-opts-math 0.2.0+alpha.9.9
	   |-- c2me-opts-scheduling 0.2.0+alpha.9.9
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.9.9
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.9.9
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.9.9
	   |-- c2me-server-utils 0.2.0+alpha.9.9
	   |-- c2me-threading-chunkio 0.2.0+alpha.9.9
	   |-- c2me-threading-lighting 0.2.0+alpha.9.9
	   |-- c2me-threading-scheduling 0.2.0+alpha.9.9
	   |-- c2me-threading-worldgen 0.2.0+alpha.9.9
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cfarmersint 0.0.2
	- chesttracker 1.1.18
	   |-- libgui 6.3.0+1.19
	   |    |-- jankson 4.1.1+j1.2.1
	   |    \-- libninepatch 1.1.0
	   \-- whereisit 1.14.13
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- cobblemon 1.3.1+1.19.2
	- cobblemonextras 1.0.4+1.19.2
	- cobblemonmikefx 0.4.0+1.19.2
	- cobblemonmikeskills 0.6.0+1.19.2
	- cobblepedia 0.4.4+1.19.2
	- create 0.5.1-b-build.1089+mc1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.8.a-5
	   |-- forge_tags 3.0
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib_accessors 2.1.1038+1.19.2
	   |-- porting_lib_base 2.1.1038+1.19.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    |-- porting_lib_constants 2.1.1038+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.1038+1.19.2
	   |    |-- porting_lib_loot 2.1.1038+1.19.2
	   |    |-- porting_lib_model_generators 2.1.1038+1.19.2
	   |    |-- porting_lib_model_loader 2.1.1038+1.19.2
	   |    |-- porting_lib_models 2.1.1038+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- porting_lib_entity 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- porting_lib_extensions 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- porting_lib_fake_players 2.1.1038+1.19.2
	   |-- porting_lib_networking 2.1.1038+1.19.2
	   |-- porting_lib_obj_loader 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    |-- porting_lib_constants 2.1.1038+1.19.2
	   |    \-- porting_lib_model_loader 2.1.1038+1.19.2
	   |-- porting_lib_transfer 2.1.1038+1.19.2
	   |    |-- porting_lib_attributes 2.1.1038+1.19.2
	   |    |-- porting_lib_common 2.1.1038+1.19.2
	   |    \-- porting_lib_constants 2.1.1038+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.58-MC1.19.2
	- distinguishedpotions 4.0.1
	- dynamicfps 2.2.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- emi 1.0.5+1.19.2+fabric
	- emiffect 0.1.5+mc1.19.2
	- emitrades 1.0.2+mc1.19.2
	- enchanting-table-descriptions 0.1.0+1.19
	- enchdesc 13.0.14
	- enhancedblockentities 0.7.2+1.19.2
	   |-- advanced_runtime_resource_pack 0.6.2
	   \-- spruceui 4.0.0+1.19
	- entityculling 1.6.1-mc1.19.2
	- exordium 1.0.2-mc1.19.2
	- extrasounds 2.3.1+1.19.2-1.19.1
	   |-- advanced_runtime_resource_pack 0.6.2
	   \-- soundcategories 1.2.4+1.19
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.3+kotlin.1.8.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.21
	- fabricshieldlib 1.7-1.19.2
	   |-- midnightlib 1.0.0
	   \-- mm 2.3
	- fabrictailor 2.0.1
	   |-- config2brigadier 1.2.1
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- farmersdelight 1.19.2-1.3.9
	- farmersknives 2.4
	- fastload 2.6.11
	- ferritecore 5.0.3
	- fightorflight 0.4.11-12
	- flowerymooblooms 1.0.0
	- forgeconfigapiport 4.2.11
	- forgetmechunk 1.0.4-1.18.X-1.19.X
	- friendsandfoes 1.8.4
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- fusion 1.0.3
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- globalpacks 1.14.3.1_fabric
	- graveyard 2.3.2
	   \-- omega-config 1.2.2-1.18.1
	- guarding 1.19.2+2.2.0
	- iceberg 1.0.46
	- immediatelyfast 1.1.12
	   \-- net_lenni0451_reflect 1.1.0
	- indium 1.0.9+mc1.19.2
	- inventoryhud 3.4.7
	- inventoryprofilesnext 1.9.4
	- inventorytabs 0.9.beta-1.19.x
	- invmove 0.8.2
	- itemborders 1.1.6
	- java 17
	- journeymap 5.9.7
	   \-- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- lazydfu 0.1.3
	- legendarytooltips 1.3.3
	- libipn 2.0.4
	- lithium 0.11.1
	- memoryleakfix 1.0.0
	- methane 1.7
	- minecraft 1.19.2
	- modmenu 4.2.0-beta.2
	- moreculling 1.19.1-0.17.0
	   \-- conditional-mixin 0.3.0
	- no-resource-pack-warnings 1.1.1
	- nochatreports 1.19.2-v1.13.12
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- patchoulibutton 1.0.2
	- phosphor 0.8.1
	- player-animator 1.0.2
	- prism 1.0.3
	- puzzleslib 4.3.12
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- raised 1.2.2
	- rechiseled 1.1.0-b
	- recipe-book-is-pain 0.9.4-1.19.2
	   |-- dark-matter-base 0.6.0-1.19.2
	   |    \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- dark-matter-enums 0.6.0-1.19.2
	   |-- dark-matter-minecraft 0.6.0-1.19.2
	   \-- dark-matter-recipe-book 0.6.0-1.19.2
	- robinhood 1.2.3
	- simplyswords 1.43.0-1.19.2
	- smoothboot 1.19-1.7.1
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- supermartijn642configlib 1.1.6
	- supermartijn642corelib 1.1.10+a
	- trinkets 3.4.2
	- ultris_mr 5.6.7g
	- vmp 0.2.0+beta.7.30
	- weaponmaster 1-19
	- yet-another-config-lib 2.2.0-for-1.19.2
[19:25:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/dex/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:25:52] [main/INFO]: Compatibility level set to JAVA_17
[19:25:52] [main/WARN]: Reference map 'axolotl-item-fix-refmap.json' for axolotlitemfix.mixins.json could not be read. If this is a development environment you can ignore this message
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[19:25:53] [main/INFO]: Disabling com.ishland.c2me.client.uncapvd.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[19:25:53] [main/INFO]: Disabling com.ishland.c2me.notickvd.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.threading.scheduling.mixin
[19:25:53] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[19:25:53] [main/INFO]: Disabling com.ishland.c2me.threading.worldgen.mixin
[19:25:54] [main/WARN]: Reference map 'InvMove-mc1.19_fabric-refmap.json' for invmove-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[19:25:54] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 2 override(s) found
[19:25:55] [main/WARN]: Reference map 'simplyswords-common-refmap.json' for simplyswords-common.mixins.json could not be read. If this is a development environment you can ignore this message
[19:25:55] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[19:25:55] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[19:25:57] [main/WARN]: Error loading class: mezz/jei/library/load/PluginCaller (java.lang.ClassNotFoundException: mezz/jei/library/load/PluginCaller)
[19:25:59] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[19:26:00] [main/WARN]: Error loading class: nukeduck/armorchroma/GuiArmor (java.lang.ClassNotFoundException: nukeduck/armorchroma/GuiArmor)
[19:26:01] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[19:26:01] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton, vmp]) disables it and children
[19:26:03] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
[19:26:03] [main/WARN]: Error loading class: com/simibubi/create/content/curiosities/armor/CopperBacktankArmorLayer (java.lang.ClassNotFoundException: com/simibubi/create/content/curiosities/armor/CopperBacktankArmorLayer)
[19:26:03] [main/WARN]: Error loading class: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient (java.lang.ClassNotFoundException: com/simibubi/create/content/curiosities/toolbox/ToolboxHandlerClient)
[19:26:03] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/structureMovement/interaction/controls/TrainHUD)
[19:26:03] [main/WARN]: Error loading class: nourl/mythicmetals/abilities/Abilities (java.lang.ClassNotFoundException: nourl/mythicmetals/abilities/Abilities)
[19:26:03] [main/WARN]: @Mixin target nourl.mythicmetals.abilities.Abilities was not found simplyswords.mixins.json:MythicMetalsAbilityMixin from mod simplyswords
[19:26:03] [main/WARN]: Error loading class: nourl/mythicmetals/MythicMetals (java.lang.ClassNotFoundException: nourl/mythicmetals/MythicMetals)
[19:26:03] [main/WARN]: @Mixin target nourl.mythicmetals.MythicMetals was not found simplyswords.mixins.json:MythicMetalsInitMixin from mod simplyswords
[19:26:04] [main/INFO]: [MemoryLeakFix] Will be applying 4 memory leak fixes!
[19:26:04] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, entityMemoriesLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[19:26:09] [main/INFO]: I used the json to destroy the json
[19:26:10] [main/INFO]: Smooth Boot config initialized
[19:26:13] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[19:26:13] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[19:26:13] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.19.2-77-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$ehg000$patchouli$addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.19.2-77-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$ehg000$patchouli$addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method convertTooltipComponents(Ljava/util/List;)Ljava/util/List; in bebooks.mixins.json:ScreenMixin from mod bebooks failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap better-enchanted-books-1.19.4-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.19.2-77-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$ehg000$patchouli$addContext(class_6396.java:1016) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 5 more
```
</details>

**Environment:**
 - Minecraft Version [1.19.2]
 - Mod Version [0.9.4 fabric]

**Additional context**
Reading a bit the log, seems like the issue is that mod is mixing minecraft items and Botania ones, so I'm not totally sure if it's this mod issue or botania ones.

The issue is solved if I disable botania or this mod.

**Comment by AnidemDex** [comment]
I'll let open this issue, but reading the crash again doesn't seems totally related to botania, but maybe other mods too? Not totally sure

**Comment by AnidemDex** [comment]
Nope, is not this mod fault. Sorry for reporting an issue
